FROM node:20-alpine3.16 as build
WORKDIR /clientapp
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build


FROM nginx:latest
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=build /clientapp/dist /var/www/html/
EXPOSE 3000