# docker-compose --file docker-compose.dev.yml up --build -d
# docker system prune --volumes
# for pinggy.io

services:
  # npmanager:
  #   image: 'jc21/nginx-proxy-manager:latest'
  #   restart: unless-stopped
  #   ports:
  #     # These ports are in format <host-port>:<container-port>
  #     - '80:80' # Public HTTP Port
  #     - '443:443' # Public HTTPS Port
  #     - '81:81' # Admin Web Port
  #   networks:
  #     - backendapp_net
      
  backendapp:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/backend:/backendapp
      - ${PWD}/backend/node_modules:/backendapp/node_modules
    environment:
      TZ: 'Europe/Moscow'
      NODE_ENV: development
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TP_API_URL: https://api.timepad.ru/v1/events.json
      TP_API_TOKEN: ${TP_API_TOKEN}
      TP_orgIdKiosk: ${TP_orgIdKiosk}
      TP_orgIdGrky: ${TP_orgIdGrky}
      TP_orgIdStand: ${TP_orgIdStand}
      TP_orgId52: ${TP_orgId52}
    networks:
      - backendapp_net
    depends_on:
      - db

  clientapp:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ${PWD}/client:/clientapp
      - ${PWD}/client/node_modules:/clientapp/node_modules
    networks:
      - backendapp_net
    depends_on:
      - backendapp

  db:
    container_name: database
    image: postgres:15.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/src/database/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    mem_limit: 512m
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "-E UTF8 --lc-collate='ru_RU.utf8' --lc-ctype='ru_RU.utf8'"
      PGTZ: 'Europe/Moscow'
      TZ: 'Europe/Moscow'
    ports:
      - 5432:5432
    networks:
      - backendapp_net

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backendapp
      - clientapp
    networks:
      - backendapp_net

volumes:
  db_data:

networks:
  backendapp_net:
